import { defineLazyLayerNode } from "./base";
import * as zod from "zod";
export const export_models = defineLazyLayerNode({
  module_name: "export_models",
  params: {},
  options: ["TFSMLayer"],
  nodes: [{
    "class_name": "TFSMLayer",
    "modules_path": "keras.src.export.export_lib",
    "params": [
      'filepath : "serve",',
      'call_endpoint : "None",',
      'call_training_endpoint : "True",',
      'trainable : "None",',
      'dtype : "None",',
    ],
    "parse_params": [],
  }],
});

export const activations = defineLazyLayerNode({
  module_name: "activations",
  params: {
    
  },
  options: ["Activation", "ELU", "LeakyReLU", "PReLU", "ReLU", "Softmax"],
  nodes: [{
    "class_name": "Activation",
    "modules_path": "keras.src.layers.activations.activation",
    "params": ['activation : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "ELU",
    "modules_path": "keras.src.layers.activations.elu",
    "params": ['alpha : "1.0",'],
    "parse_params": [],
  }, {
    "class_name": "LeakyReLU",
    "modules_path": "keras.src.layers.activations.leaky_relu",
    "params": ['negative_slope : "0.3",'],
    "parse_params": [],
  }, {
    "class_name": "PReLU",
    "modules_path": "keras.src.layers.activations.prelu",
    "params": [
      'alpha_initializer : "Zeros",',
      'alpha_regularizer : "None",',
      'alpha_constraint : "None",',
      'shared_axes : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "ReLU",
    "modules_path": "keras.src.layers.activations.relu",
    "params": [
      'max_value : "None",',
      'negative_slope : "0.0",',
      'threshold : "0.0",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Softmax",
    "modules_path": "keras.src.layers.activations.softmax",
    "params": ['axis : "-1",'],
    "parse_params": [],
  }],
});

export const attention = defineLazyLayerNode({
  module_name: "attention",
  params: {},
  options: [
    "AdditiveAttention",
    "Attention",
    "GroupedQueryAttention",
    "MultiHeadAttention",
  ],
  nodes: [{
    "class_name": "AdditiveAttention",
    "modules_path": "keras.src.layers.attention.additive_attention",
    "params": ['use_scale : "True",', 'dropout : "0.0",'],
    "parse_params": [],
  }, {
    "class_name": "Attention",
    "modules_path": "keras.src.layers.attention.attention",
    "params": [
      'use_scale : "False",',
      'score_mode : "dot",',
      'dropout : "0.0",',
      'seed : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "GroupedQueryAttention",
    "modules_path": "keras.src.layers.attention.grouped_query_attention",
    "params": [
      'head_dim : "0.0",',
      'num_query_heads : "True",',
      'num_key_value_heads : "glorot_uniform",',
      'dropout : "zeros",',
      'use_bias : "None",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "NoneType",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "MultiHeadAttention",
    "modules_path": "keras.src.layers.attention.multi_head_attention",
    "params": [
      'num_heads : "None",',
      'key_dim : "0.0",',
      'value_dim : "True",',
      'dropout : "None",',
      'use_bias : "None",',
      'output_shape : "glorot_uniform",',
      'attention_axes : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }],
});

export const convolutional = defineLazyLayerNode({
  module_name: "convolutional",
  params: {},
  options: [
    "Conv1D",
    "Conv1D",
    "Conv1DTranspose",
    "Conv1DTranspose",
    "Conv2D",
    "Conv2D",
    "Conv2DTranspose",
    "Conv2DTranspose",
    "Conv3D",
    "Conv3D",
    "Conv3DTranspose",
    "Conv3DTranspose",
    "DepthwiseConv1D",
    "DepthwiseConv2D",
    "SeparableConv1D",
    "SeparableConv1D",
    "SeparableConv2D",
    "SeparableConv2D",
  ],
  nodes: [{
    "class_name": "Conv1D",
    "modules_path": "keras.src.layers.convolutional.conv1d",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'groups : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv1D",
    "modules_path": "keras.src.layers.convolutional.conv1d",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'groups : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv1DTranspose",
    "modules_path": "keras.src.layers.convolutional.conv1d_transpose",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "None",',
      'dilation_rate : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv1DTranspose",
    "modules_path": "keras.src.layers.convolutional.conv1d_transpose",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "None",',
      'dilation_rate : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv2D",
    "modules_path": "keras.src.layers.convolutional.conv2d",
    "params": [
      'filters : "(1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1)",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'groups : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv2D",
    "modules_path": "keras.src.layers.convolutional.conv2d",
    "params": [
      'filters : "(1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1)",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'groups : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv2DTranspose",
    "modules_path": "keras.src.layers.convolutional.conv2d_transpose",
    "params": [
      'filters : "(1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1)",',
      'data_format : "None",',
      'dilation_rate : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv2DTranspose",
    "modules_path": "keras.src.layers.convolutional.conv2d_transpose",
    "params": [
      'filters : "(1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1)",',
      'data_format : "None",',
      'dilation_rate : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv3D",
    "modules_path": "keras.src.layers.convolutional.conv3d",
    "params": [
      'filters : "(1, 1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1, 1)",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'groups : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv3D",
    "modules_path": "keras.src.layers.convolutional.conv3d",
    "params": [
      'filters : "(1, 1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1, 1)",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'groups : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv3DTranspose",
    "modules_path": "keras.src.layers.convolutional.conv3d_transpose",
    "params": [
      'filters : "(1, 1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1, 1)",',
      'data_format : "None",',
      'dilation_rate : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Conv3DTranspose",
    "modules_path": "keras.src.layers.convolutional.conv3d_transpose",
    "params": [
      'filters : "(1, 1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1, 1)",',
      'data_format : "None",',
      'dilation_rate : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "DepthwiseConv1D",
    "modules_path": "keras.src.layers.convolutional.depthwise_conv1d",
    "params": [
      'kernel_size : "1",',
      'strides : "valid",',
      'padding : "1",',
      'depth_multiplier : "None",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'activation : "True",',
      'use_bias : "glorot_uniform",',
      'depthwise_initializer : "zeros",',
      'bias_initializer : "None",',
      'depthwise_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'depthwise_constraint : "None",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "DepthwiseConv2D",
    "modules_path": "keras.src.layers.convolutional.depthwise_conv2d",
    "params": [
      'kernel_size : "(1, 1)",',
      'strides : "valid",',
      'padding : "1",',
      'depth_multiplier : "None",',
      'data_format : "(1, 1)",',
      'dilation_rate : "None",',
      'activation : "True",',
      'use_bias : "glorot_uniform",',
      'depthwise_initializer : "zeros",',
      'bias_initializer : "None",',
      'depthwise_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'depthwise_constraint : "None",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SeparableConv1D",
    "modules_path": "keras.src.layers.convolutional.separable_conv1d",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'depth_multiplier : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "glorot_uniform",',
      'depthwise_initializer : "zeros",',
      'pointwise_initializer : "None",',
      'bias_initializer : "None",',
      'depthwise_regularizer : "None",',
      'pointwise_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'depthwise_constraint : "None",',
      'pointwise_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SeparableConv1D",
    "modules_path": "keras.src.layers.convolutional.separable_conv1d",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'depth_multiplier : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "glorot_uniform",',
      'depthwise_initializer : "zeros",',
      'pointwise_initializer : "None",',
      'bias_initializer : "None",',
      'depthwise_regularizer : "None",',
      'pointwise_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'depthwise_constraint : "None",',
      'pointwise_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SeparableConv2D",
    "modules_path": "keras.src.layers.convolutional.separable_conv2d",
    "params": [
      'filters : "(1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1)",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'depth_multiplier : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "glorot_uniform",',
      'depthwise_initializer : "zeros",',
      'pointwise_initializer : "None",',
      'bias_initializer : "None",',
      'depthwise_regularizer : "None",',
      'pointwise_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'depthwise_constraint : "None",',
      'pointwise_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SeparableConv2D",
    "modules_path": "keras.src.layers.convolutional.separable_conv2d",
    "params": [
      'filters : "(1, 1)",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "(1, 1)",',
      'data_format : "1",',
      'dilation_rate : "None",',
      'depth_multiplier : "True",',
      'activation : "glorot_uniform",',
      'use_bias : "glorot_uniform",',
      'depthwise_initializer : "zeros",',
      'pointwise_initializer : "None",',
      'bias_initializer : "None",',
      'depthwise_regularizer : "None",',
      'pointwise_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'depthwise_constraint : "None",',
      'pointwise_constraint : "NoneType",',
      'bias_constraint : "NoneType",',
    ],
    "parse_params": [],
  }],
});

export const core = defineLazyLayerNode({
  module_name: "core",
  params: {},
  options: [
    "Dense",
    "EinsumDense",
    "Embedding",
    "Identity",
    "InputLayer",
    "Lambda",
    "Masking",
    "Wrapper",
  ],
  nodes: [{
    "class_name": "Dense",
    "modules_path": "keras.src.layers.core.dense",
    "params": [
      'units : "None",',
      'activation : "True",',
      'use_bias : "glorot_uniform",',
      'kernel_initializer : "zeros",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "None",',
      'bias_constraint : "None",',
      'lora_rank : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "EinsumDense",
    "modules_path": "keras.src.layers.core.einsum_dense",
    "params": [
      'equation : "None",',
      'output_shape : "None",',
      'activation : "glorot_uniform",',
      'bias_axes : "zeros",',
      'kernel_initializer : "None",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'bias_regularizer : "None",',
      'kernel_constraint : "None",',
      'bias_constraint : "NoneType",',
      'lora_rank : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Embedding",
    "modules_path": "keras.src.layers.core.embedding",
    "params": [
      'input_dim : "uniform",',
      'output_dim : "None",',
      'embeddings_initializer : "None",',
      'embeddings_regularizer : "False",',
      'embeddings_constraint : "None",',
      'mask_zero : "None",',
      'weights : "NoneType",',
      'lora_rank : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Identity",
    "modules_path": "keras.src.layers.core.identity",
    "params": [],
    "parse_params": [],
  }, {
    "class_name": "InputLayer",
    "modules_path": "keras.src.layers.core.input_layer",
    "params": [
      'shape : "None",',
      'batch_size : "None",',
      'dtype : "None",',
      'sparse : "None",',
      'batch_shape : "None",',
      'input_tensor : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Lambda",
    "modules_path": "keras.src.layers.core.lambda_layer",
    "params": [
      'function : "None",',
      'output_shape : "None",',
      'mask : "None",',
      'arguments : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Masking",
    "modules_path": "keras.src.layers.core.masking",
    "params": ['mask_value : "0.0",'],
    "parse_params": [],
  }, {
    "class_name": "Wrapper",
    "modules_path": "keras.src.layers.core.wrapper",
    "params": ['layer : "NoneType",'],
    "parse_params": [],
  }],
});

export const layers = defineLazyLayerNode({
  module_name: "layers",
  params: {},
  options: ["InputSpec", "Layer"],
  nodes: [{
    "class_name": "InputSpec",
    "modules_path": "keras.src.layers.input_spec",
    "params": [
      'dtype : "None",',
      'shape : "None",',
      'ndim : "None",',
      'max_ndim : "None",',
      'min_ndim : "None",',
      'axes : "None",',
      'allow_last_axis_squeeze : "False",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Layer",
    "modules_path": "keras.src.layers.layer",
    "params": [],
    "parse_params": [],
  }],
});

export const merging = defineLazyLayerNode({
  module_name: "merging",
  params: {},
  options: [
    "Add",
    "Average",
    "Concatenate",
    "Dot",
    "Maximum",
    "Minimum",
    "Multiply",
    "Subtract",
  ],
  nodes: [{
    "class_name": "Add",
    "modules_path": "keras.src.layers.merging.add",
    "params": [],
    "parse_params": [],
  }, {
    "class_name": "Average",
    "modules_path": "keras.src.layers.merging.average",
    "params": [],
    "parse_params": [],
  }, {
    "class_name": "Concatenate",
    "modules_path": "keras.src.layers.merging.concatenate",
    "params": ['axis : "-1",'],
    "parse_params": [],
  }, {
    "class_name": "Dot",
    "modules_path": "keras.src.layers.merging.dot",
    "params": ['axes : "False",', 'normalize : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "Maximum",
    "modules_path": "keras.src.layers.merging.maximum",
    "params": [],
    "parse_params": [],
  }, {
    "class_name": "Minimum",
    "modules_path": "keras.src.layers.merging.minimum",
    "params": [],
    "parse_params": [],
  }, {
    "class_name": "Multiply",
    "modules_path": "keras.src.layers.merging.multiply",
    "params": [],
    "parse_params": [],
  }, {
    "class_name": "Subtract",
    "modules_path": "keras.src.layers.merging.subtract",
    "params": [],
    "parse_params": [],
  }],
});

export const normalization = defineLazyLayerNode({
  module_name: "normalization",
  params: {},
  options: [
    "BatchNormalization",
    "GroupNormalization",
    "LayerNormalization",
    "SpectralNormalization",
    "UnitNormalization",
  ],
  nodes: [{
    "class_name": "BatchNormalization",
    "modules_path": "keras.src.layers.normalization.batch_normalization",
    "params": [
      'axis : "-1",',
      'momentum : "0.99",',
      'epsilon : "0.001",',
      'center : "True",',
      'scale : "True",',
      'beta_initializer : "zeros",',
      'gamma_initializer : "ones",',
      'moving_mean_initializer : "zeros",',
      'moving_variance_initializer : "ones",',
      'beta_regularizer : "None",',
      'gamma_regularizer : "None",',
      'beta_constraint : "None",',
      'gamma_constraint : "None",',
      'synchronized : "False",',
    ],
    "parse_params": [],
  }, {
    "class_name": "GroupNormalization",
    "modules_path": "keras.src.layers.normalization.group_normalization",
    "params": [
      'groups : "32",',
      'axis : "-1",',
      'epsilon : "0.001",',
      'center : "True",',
      'scale : "True",',
      'beta_initializer : "zeros",',
      'gamma_initializer : "ones",',
      'beta_regularizer : "None",',
      'gamma_regularizer : "None",',
      'beta_constraint : "None",',
      'gamma_constraint : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "LayerNormalization",
    "modules_path": "keras.src.layers.normalization.layer_normalization",
    "params": [
      'axis : "-1",',
      'epsilon : "0.001",',
      'center : "True",',
      'scale : "True",',
      'rms_scaling : "False",',
      'beta_initializer : "zeros",',
      'gamma_initializer : "ones",',
      'beta_regularizer : "None",',
      'gamma_regularizer : "None",',
      'beta_constraint : "None",',
      'gamma_constraint : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SpectralNormalization",
    "modules_path": "keras.src.layers.normalization.spectral_normalization",
    "params": ['layer : "1",', 'power_iterations : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "UnitNormalization",
    "modules_path": "keras.src.layers.normalization.unit_normalization",
    "params": ['axis : "-1",'],
    "parse_params": [],
  }],
});

export const pooling = defineLazyLayerNode({
  module_name: "pooling",
  params: {},
  options: [
    "AveragePooling1D",
    "AveragePooling1D",
    "AveragePooling2D",
    "AveragePooling2D",
    "AveragePooling3D",
    "AveragePooling3D",
    "GlobalAveragePooling1D",
    "GlobalAveragePooling1D",
    "GlobalAveragePooling2D",
    "GlobalAveragePooling2D",
    "GlobalAveragePooling3D",
    "GlobalAveragePooling3D",
    "GlobalMaxPooling1D",
    "GlobalMaxPooling1D",
    "GlobalMaxPooling2D",
    "GlobalMaxPooling2D",
    "GlobalMaxPooling3D",
    "GlobalMaxPooling3D",
    "MaxPooling1D",
    "MaxPooling1D",
    "MaxPooling2D",
    "MaxPooling2D",
    "MaxPooling3D",
    "MaxPooling3D",
  ],
  nodes: [{
    "class_name": "AveragePooling1D",
    "modules_path": "keras.src.layers.pooling.average_pooling1d",
    "params": [
      'pool_size : "None",',
      'strides : "valid",',
      'padding : "None",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "AveragePooling1D",
    "modules_path": "keras.src.layers.pooling.average_pooling1d",
    "params": [
      'pool_size : "None",',
      'strides : "valid",',
      'padding : "None",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "AveragePooling2D",
    "modules_path": "keras.src.layers.pooling.average_pooling2d",
    "params": [
      'pool_size : "None",',
      'strides : "valid",',
      'padding : "None",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "AveragePooling2D",
    "modules_path": "keras.src.layers.pooling.average_pooling2d",
    "params": [
      'pool_size : "None",',
      'strides : "valid",',
      'padding : "None",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "AveragePooling3D",
    "modules_path": "keras.src.layers.pooling.average_pooling3d",
    "params": [
      'pool_size : "None",',
      'strides : "valid",',
      'padding : "None",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "AveragePooling3D",
    "modules_path": "keras.src.layers.pooling.average_pooling3d",
    "params": [
      'pool_size : "None",',
      'strides : "valid",',
      'padding : "None",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "GlobalAveragePooling1D",
    "modules_path": "keras.src.layers.pooling.global_average_pooling1d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalAveragePooling1D",
    "modules_path": "keras.src.layers.pooling.global_average_pooling1d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalAveragePooling2D",
    "modules_path": "keras.src.layers.pooling.global_average_pooling2d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalAveragePooling2D",
    "modules_path": "keras.src.layers.pooling.global_average_pooling2d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalAveragePooling3D",
    "modules_path": "keras.src.layers.pooling.global_average_pooling3d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalAveragePooling3D",
    "modules_path": "keras.src.layers.pooling.global_average_pooling3d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalMaxPooling1D",
    "modules_path": "keras.src.layers.pooling.global_max_pooling1d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalMaxPooling1D",
    "modules_path": "keras.src.layers.pooling.global_max_pooling1d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalMaxPooling2D",
    "modules_path": "keras.src.layers.pooling.global_max_pooling2d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalMaxPooling2D",
    "modules_path": "keras.src.layers.pooling.global_max_pooling2d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalMaxPooling3D",
    "modules_path": "keras.src.layers.pooling.global_max_pooling3d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "GlobalMaxPooling3D",
    "modules_path": "keras.src.layers.pooling.global_max_pooling3d",
    "params": ['data_format : "None",', 'keepdims : "False",'],
    "parse_params": [],
  }, {
    "class_name": "MaxPooling1D",
    "modules_path": "keras.src.layers.pooling.max_pooling1d",
    "params": [
      'pool_size : "2",',
      'strides : "None",',
      'padding : "valid",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "MaxPooling1D",
    "modules_path": "keras.src.layers.pooling.max_pooling1d",
    "params": [
      'pool_size : "2",',
      'strides : "None",',
      'padding : "valid",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "MaxPooling2D",
    "modules_path": "keras.src.layers.pooling.max_pooling2d",
    "params": [
      'pool_size : "(2, 2)",',
      'strides : "None",',
      'padding : "valid",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "MaxPooling2D",
    "modules_path": "keras.src.layers.pooling.max_pooling2d",
    "params": [
      'pool_size : "(2, 2)",',
      'strides : "None",',
      'padding : "valid",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "MaxPooling3D",
    "modules_path": "keras.src.layers.pooling.max_pooling3d",
    "params": [
      'pool_size : "(2, 2, 2)",',
      'strides : "None",',
      'padding : "valid",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "MaxPooling3D",
    "modules_path": "keras.src.layers.pooling.max_pooling3d",
    "params": [
      'pool_size : "(2, 2, 2)",',
      'strides : "None",',
      'padding : "valid",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }],
});

export const preprocessing = defineLazyLayerNode({
  module_name: "preprocessing",
  params: {},
  options: [
    "MelSpectrogram",
    "CategoryEncoding",
    "CenterCrop",
    "Discretization",
    "HashedCrossing",
    "Hashing",
    "IntegerLookup",
    "Normalization",
    "RandomBrightness",
    "RandomContrast",
    "RandomCrop",
    "RandomFlip",
    "RandomRotation",
    "RandomTranslation",
    "RandomZoom",
    "Rescaling",
    "Resizing",
    "StringLookup",
    "TextVectorization",
  ],
  nodes: [{
    "class_name": "MelSpectrogram",
    "modules_path": "keras.src.layers.preprocessing.audio_preprocessing",
    "params": [
      'fft_length : "2048",',
      'sequence_stride : "512",',
      'sequence_length : "None",',
      'window : "hann",',
      'sampling_rate : "16000",',
      'num_mel_bins : "128",',
      'min_freq : "20.0",',
      'max_freq : "None",',
      'power_to_db : "True",',
      'top_db : "80.0",',
      'mag_exp : "2.0",',
      'min_power : "1e-10",',
      'ref_power : "1.0",',
    ],
    "parse_params": [],
  }, {
    "class_name": "CategoryEncoding",
    "modules_path": "keras.src.layers.preprocessing.category_encoding",
    "params": [
      'num_tokens : "None",',
      'output_mode : "multi_hot",',
      'sparse : "False",',
    ],
    "parse_params": [],
  }, {
    "class_name": "CenterCrop",
    "modules_path": "keras.src.layers.preprocessing.center_crop",
    "params": [
      'height : "None",',
      'width : "NoneType",',
      'data_format : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Discretization",
    "modules_path": "keras.src.layers.preprocessing.discretization",
    "params": [
      'bin_boundaries : "None",',
      'num_bins : "None",',
      'epsilon : "0.01",',
      'output_mode : "int",',
      'sparse : "False",',
      'dtype : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "HashedCrossing",
    "modules_path": "keras.src.layers.preprocessing.hashed_crossing",
    "params": [
      'num_bins : "int",',
      'output_mode : "False",',
      'sparse : "None",',
      'dtype : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Hashing",
    "modules_path": "keras.src.layers.preprocessing.hashing",
    "params": [
      'num_bins : "None",',
      'mask_value : "None",',
      'salt : "int",',
      'output_mode : "False",',
      'sparse : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "IntegerLookup",
    "modules_path": "keras.src.layers.preprocessing.integer_lookup",
    "params": [
      'max_tokens : "None",',
      'num_oov_indices : "1",',
      'mask_token : "None",',
      'oov_token : "-1",',
      'vocabulary : "None",',
      'vocabulary_dtype : "int64",',
      'idf_weights : "None",',
      'invert : "False",',
      'output_mode : "int",',
      'sparse : "False",',
      'pad_to_max_tokens : "False",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Normalization",
    "modules_path": "keras.src.layers.preprocessing.normalization",
    "params": [
      'axis : "-1",',
      'mean : "None",',
      'variance : "None",',
      'invert : "False",',
    ],
    "parse_params": [],
  }, {
    "class_name": "RandomBrightness",
    "modules_path": "keras.src.layers.preprocessing.random_brightness",
    "params": [
      'factor : "(0, 255)",',
      'value_range : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "RandomContrast",
    "modules_path": "keras.src.layers.preprocessing.random_contrast",
    "params": ['factor : "None",', 'seed : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "RandomCrop",
    "modules_path": "keras.src.layers.preprocessing.random_crop",
    "params": [
      'height : "None",',
      'width : "None",',
      'seed : "None",',
      'data_format : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "RandomFlip",
    "modules_path": "keras.src.layers.preprocessing.random_flip",
    "params": ['mode : "horizontal_and_vertical",', 'seed : "None",'],
    "parse_params": [],
  }, {
    "class_name": "RandomRotation",
    "modules_path": "keras.src.layers.preprocessing.random_rotation",
    "params": [
      'factor : "reflect",',
      'fill_mode : "bilinear",',
      'interpolation : "None",',
      'seed : "0.0",',
      'fill_value : "(0, 255)",',
      'value_range : "None",',
      'data_format : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "RandomTranslation",
    "modules_path": "keras.src.layers.preprocessing.random_translation",
    "params": [
      'height_factor : "reflect",',
      'width_factor : "bilinear",',
      'fill_mode : "None",',
      'interpolation : "0.0",',
      'seed : "None",',
      'fill_value : "NoneType",',
      'data_format : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "RandomZoom",
    "modules_path": "keras.src.layers.preprocessing.random_zoom",
    "params": [
      'height_factor : "None",',
      'width_factor : "reflect",',
      'fill_mode : "bilinear",',
      'interpolation : "None",',
      'seed : "0.0",',
      'fill_value : "None",',
      'data_format : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Rescaling",
    "modules_path": "keras.src.layers.preprocessing.rescaling",
    "params": ['scale : "0.0",', 'offset : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "Resizing",
    "modules_path": "keras.src.layers.preprocessing.resizing",
    "params": [
      'height : "bilinear",',
      'width : "False",',
      'interpolation : "False",',
      'crop_to_aspect_ratio : "constant",',
      'pad_to_aspect_ratio : "0.0",',
      'fill_mode : "None",',
      'fill_value : "NoneType",',
      'data_format : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "StringLookup",
    "modules_path": "keras.src.layers.preprocessing.string_lookup",
    "params": [
      'max_tokens : "None",',
      'num_oov_indices : "1",',
      'mask_token : "None",',
      'oov_token : "[UNK]",',
      'vocabulary : "None",',
      'idf_weights : "None",',
      'invert : "False",',
      'output_mode : "int",',
      'pad_to_max_tokens : "False",',
      'sparse : "False",',
      'encoding : "utf-8",',
    ],
    "parse_params": [],
  }, {
    "class_name": "TextVectorization",
    "modules_path": "keras.src.layers.preprocessing.text_vectorization",
    "params": [
      'max_tokens : "None",',
      'standardize : "lower_and_strip_punctuation",',
      'split : "whitespace",',
      'ngrams : "None",',
      'output_mode : "int",',
      'output_sequence_length : "None",',
      'pad_to_max_tokens : "False",',
      'vocabulary : "None",',
      'idf_weights : "None",',
      'sparse : "False",',
      'ragged : "False",',
      'encoding : "utf-8",',
    ],
    "parse_params": [],
  }],
});

export const regularization = defineLazyLayerNode({
  module_name: "regularization",
  params: {},
  options: [
    "ActivityRegularization",
    "Dropout",
    "GaussianDropout",
    "GaussianNoise",
    "SpatialDropout1D",
    "SpatialDropout2D",
    "SpatialDropout3D",
  ],
  nodes: [{
    "class_name": "ActivityRegularization",
    "modules_path": "keras.src.layers.regularization.activity_regularization",
    "params": ['l1 : "0.0",', 'l2 : "0.0",'],
    "parse_params": [],
  }, {
    "class_name": "Dropout",
    "modules_path": "keras.src.layers.regularization.dropout",
    "params": ['rate : "None",', 'noise_shape : "None",', 'seed : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "GaussianDropout",
    "modules_path": "keras.src.layers.regularization.gaussian_dropout",
    "params": ['rate : "None",', 'seed : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "GaussianNoise",
    "modules_path": "keras.src.layers.regularization.gaussian_noise",
    "params": ['stddev : "None",', 'seed : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "SpatialDropout1D",
    "modules_path": "keras.src.layers.regularization.spatial_dropout",
    "params": ['rate : "None",', 'seed : "None",', 'dtype : "None",'],
    "parse_params": [],
  }, {
    "class_name": "SpatialDropout2D",
    "modules_path": "keras.src.layers.regularization.spatial_dropout",
    "params": [
      'rate : "None",',
      'data_format : "None",',
      'seed : "None",',
      'dtype : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SpatialDropout3D",
    "modules_path": "keras.src.layers.regularization.spatial_dropout",
    "params": [
      'rate : "None",',
      'data_format : "None",',
      'seed : "None",',
      'dtype : "None",',
    ],
    "parse_params": [],
  }],
});

export const reshaping = defineLazyLayerNode({
  module_name: "reshaping",
  params: {},
  options: [
    "Cropping1D",
    "Cropping2D",
    "Cropping3D",
    "Flatten",
    "Permute",
    "RepeatVector",
    "Reshape",
    "UpSampling1D",
    "UpSampling2D",
    "UpSampling3D",
    "ZeroPadding1D",
    "ZeroPadding2D",
    "ZeroPadding3D",
  ],
  nodes: [{
    "class_name": "Cropping1D",
    "modules_path": "keras.src.layers.reshaping.cropping1d",
    "params": ['cropping : "(1, 1)",'],
    "parse_params": [],
  }, {
    "class_name": "Cropping2D",
    "modules_path": "keras.src.layers.reshaping.cropping2d",
    "params": ['cropping : "((0, 0), (0, 0))",', 'data_format : "None",'],
    "parse_params": [],
  }, {
    "class_name": "Cropping3D",
    "modules_path": "keras.src.layers.reshaping.cropping3d",
    "params": [
      'cropping : "((1, 1), (1, 1), (1, 1))",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }, {
    "class_name": "Flatten",
    "modules_path": "keras.src.layers.reshaping.flatten",
    "params": ['data_format : "None",'],
    "parse_params": [],
  }, {
    "class_name": "Permute",
    "modules_path": "keras.src.layers.reshaping.permute",
    "params": ['dims : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "RepeatVector",
    "modules_path": "keras.src.layers.reshaping.repeat_vector",
    "params": ['n : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "Reshape",
    "modules_path": "keras.src.layers.reshaping.reshape",
    "params": ['target_shape : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "UpSampling1D",
    "modules_path": "keras.src.layers.reshaping.up_sampling1d",
    "params": ['size : "2",'],
    "parse_params": [],
  }, {
    "class_name": "UpSampling2D",
    "modules_path": "keras.src.layers.reshaping.up_sampling2d",
    "params": [
      'size : "(2, 2)",',
      'data_format : "None",',
      'interpolation : "nearest",',
    ],
    "parse_params": [],
  }, {
    "class_name": "UpSampling3D",
    "modules_path": "keras.src.layers.reshaping.up_sampling3d",
    "params": ['size : "(2, 2, 2)",', 'data_format : "None",'],
    "parse_params": [],
  }, {
    "class_name": "ZeroPadding1D",
    "modules_path": "keras.src.layers.reshaping.zero_padding1d",
    "params": ['padding : "1",'],
    "parse_params": [],
  }, {
    "class_name": "ZeroPadding2D",
    "modules_path": "keras.src.layers.reshaping.zero_padding2d",
    "params": ['padding : "(1, 1)",', 'data_format : "None",'],
    "parse_params": [],
  }, {
    "class_name": "ZeroPadding3D",
    "modules_path": "keras.src.layers.reshaping.zero_padding3d",
    "params": [
      'padding : "((1, 1), (1, 1), (1, 1))",',
      'data_format : "None",',
    ],
    "parse_params": [],
  }],
});

export const rnn = defineLazyLayerNode({
  module_name: "rnn",
  params: {},
  options: [
    "Bidirectional",
    "ConvLSTM1D",
    "ConvLSTM2D",
    "ConvLSTM3D",
    "GRU",
    "GRUCell",
    "LSTM",
    "LSTMCell",
    "RNN",
    "SimpleRNN",
    "SimpleRNNCell",
    "StackedRNNCells",
    "TimeDistributed",
  ],
  nodes: [{
    "class_name": "Bidirectional",
    "modules_path": "keras.src.layers.rnn.bidirectional",
    "params": [
      'layer : "concat",',
      'merge_mode : "None",',
      'weights : "None",',
      'backward_layer : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "ConvLSTM1D",
    "modules_path": "keras.src.layers.rnn.conv_lstm1d",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "tanh",',
      'dilation_rate : "sigmoid",',
      'activation : "True",',
      'recurrent_activation : "glorot_uniform",',
      'use_bias : "orthogonal",',
      'kernel_initializer : "zeros",',
      'recurrent_initializer : "True",',
      'bias_initializer : "None",',
      'unit_forget_bias : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "0.0",',
      'bias_constraint : "0.0",',
      'dropout : "None",',
      'recurrent_dropout : "False",',
      'seed : "False",',
      'return_sequences : "False",',
      'return_state : "False",',
      'go_backwards : "NoneType",',
      'stateful : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "ConvLSTM2D",
    "modules_path": "keras.src.layers.rnn.conv_lstm2d",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "tanh",',
      'dilation_rate : "sigmoid",',
      'activation : "True",',
      'recurrent_activation : "glorot_uniform",',
      'use_bias : "orthogonal",',
      'kernel_initializer : "zeros",',
      'recurrent_initializer : "True",',
      'bias_initializer : "None",',
      'unit_forget_bias : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "0.0",',
      'bias_constraint : "0.0",',
      'dropout : "None",',
      'recurrent_dropout : "False",',
      'seed : "False",',
      'return_sequences : "False",',
      'return_state : "False",',
      'go_backwards : "NoneType",',
      'stateful : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "ConvLSTM3D",
    "modules_path": "keras.src.layers.rnn.conv_lstm3d",
    "params": [
      'filters : "1",',
      'kernel_size : "valid",',
      'strides : "None",',
      'padding : "1",',
      'data_format : "tanh",',
      'dilation_rate : "sigmoid",',
      'activation : "True",',
      'recurrent_activation : "glorot_uniform",',
      'use_bias : "orthogonal",',
      'kernel_initializer : "zeros",',
      'recurrent_initializer : "True",',
      'bias_initializer : "None",',
      'unit_forget_bias : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "0.0",',
      'bias_constraint : "0.0",',
      'dropout : "None",',
      'recurrent_dropout : "False",',
      'seed : "False",',
      'return_sequences : "False",',
      'return_state : "False",',
      'go_backwards : "NoneType",',
      'stateful : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "GRU",
    "modules_path": "keras.src.layers.rnn.gru",
    "params": [
      'units : "tanh",',
      'activation : "sigmoid",',
      'recurrent_activation : "True",',
      'use_bias : "glorot_uniform",',
      'kernel_initializer : "orthogonal",',
      'recurrent_initializer : "zeros",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "None",',
      'bias_constraint : "0.0",',
      'dropout : "0.0",',
      'recurrent_dropout : "None",',
      'seed : "False",',
      'return_sequences : "False",',
      'return_state : "False",',
      'go_backwards : "False",',
      'stateful : "False",',
      'unroll : "True",',
      'reset_after : "auto",',
      'use_cudnn : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "GRUCell",
    "modules_path": "keras.src.layers.rnn.gru",
    "params": [
      'units : "tanh",',
      'activation : "sigmoid",',
      'recurrent_activation : "True",',
      'use_bias : "glorot_uniform",',
      'kernel_initializer : "orthogonal",',
      'recurrent_initializer : "zeros",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "None",',
      'bias_constraint : "0.0",',
      'dropout : "0.0",',
      'recurrent_dropout : "True",',
      'reset_after : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "LSTM",
    "modules_path": "keras.src.layers.rnn.lstm",
    "params": [
      'units : "tanh",',
      'activation : "sigmoid",',
      'recurrent_activation : "True",',
      'use_bias : "glorot_uniform",',
      'kernel_initializer : "orthogonal",',
      'recurrent_initializer : "zeros",',
      'bias_initializer : "True",',
      'unit_forget_bias : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "None",',
      'bias_constraint : "0.0",',
      'dropout : "0.0",',
      'recurrent_dropout : "None",',
      'seed : "False",',
      'return_sequences : "False",',
      'return_state : "False",',
      'go_backwards : "False",',
      'stateful : "False",',
      'unroll : "auto",',
      'use_cudnn : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "LSTMCell",
    "modules_path": "keras.src.layers.rnn.lstm",
    "params": [
      'units : "tanh",',
      'activation : "sigmoid",',
      'recurrent_activation : "True",',
      'use_bias : "glorot_uniform",',
      'kernel_initializer : "orthogonal",',
      'recurrent_initializer : "zeros",',
      'bias_initializer : "True",',
      'unit_forget_bias : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "None",',
      'bias_constraint : "0.0",',
      'dropout : "0.0",',
      'recurrent_dropout : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "RNN",
    "modules_path": "keras.src.layers.rnn.rnn",
    "params": [
      'cell : "False",',
      'return_sequences : "False",',
      'return_state : "False",',
      'go_backwards : "False",',
      'stateful : "False",',
      'unroll : "False",',
      'zero_output_for_mask : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SimpleRNN",
    "modules_path": "keras.src.layers.rnn.simple_rnn",
    "params": [
      'units : "tanh",',
      'activation : "True",',
      'use_bias : "glorot_uniform",',
      'kernel_initializer : "orthogonal",',
      'recurrent_initializer : "zeros",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'activity_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "None",',
      'bias_constraint : "0.0",',
      'dropout : "0.0",',
      'recurrent_dropout : "False",',
      'return_sequences : "False",',
      'return_state : "False",',
      'go_backwards : "False",',
      'stateful : "False",',
      'unroll : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "SimpleRNNCell",
    "modules_path": "keras.src.layers.rnn.simple_rnn",
    "params": [
      'units : "tanh",',
      'activation : "True",',
      'use_bias : "glorot_uniform",',
      'kernel_initializer : "orthogonal",',
      'recurrent_initializer : "zeros",',
      'bias_initializer : "None",',
      'kernel_regularizer : "None",',
      'recurrent_regularizer : "None",',
      'bias_regularizer : "None",',
      'kernel_constraint : "None",',
      'recurrent_constraint : "None",',
      'bias_constraint : "0.0",',
      'dropout : "0.0",',
      'recurrent_dropout : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "StackedRNNCells",
    "modules_path": "keras.src.layers.rnn.stacked_rnn_cells",
    "params": ['cells : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "TimeDistributed",
    "modules_path": "keras.src.layers.rnn.time_distributed",
    "params": ['layer : "NoneType",'],
    "parse_params": [],
  }],
});

export const legacy = defineLazyLayerNode({
  module_name: "legacy",
  params: {},
  options: ["AlphaDropout", "RandomHeight", "RandomWidth", "ThresholdedReLU"],
  nodes: [{
    "class_name": "AlphaDropout",
    "modules_path": "keras.src.legacy.layers",
    "params": ['rate : "None",', 'noise_shape : "None",', 'seed : "NoneType",'],
    "parse_params": [],
  }, {
    "class_name": "RandomHeight",
    "modules_path": "keras.src.legacy.layers",
    "params": [
      'factor : "bilinear",',
      'interpolation : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "RandomWidth",
    "modules_path": "keras.src.legacy.layers",
    "params": [
      'factor : "bilinear",',
      'interpolation : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "ThresholdedReLU",
    "modules_path": "keras.src.legacy.layers",
    "params": ['theta : "1.0",'],
    "parse_params": [],
  }],
});

export const utils = defineLazyLayerNode({
  module_name: "utils",
  params: {},
  options: ["FlaxLayer", "JaxLayer", "TorchModuleWrapper"],
  nodes: [{
    "class_name": "FlaxLayer",
    "modules_path": "keras.src.utils.jax_layer",
    "params": [
      'module : "None",',
      'method : "None",',
      'variables : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "JaxLayer",
    "modules_path": "keras.src.utils.jax_layer",
    "params": [
      'call_fn : "None",',
      'init_fn : "None",',
      'params : "None",',
      'state : "None",',
      'seed : "NoneType",',
    ],
    "parse_params": [],
  }, {
    "class_name": "TorchModuleWrapper",
    "modules_path": "keras.src.utils.torch_utils",
    "params": ['module : "None",'],
    "parse_params": [],
  }],
});
