[package]
name = "xenosphere-core"
version = "0.0.1-alpha.1"
edition = "2021"
description = "A core framework for Xenosphere"
license-file= "LICENSE"
repository = "https://github.com/Stvchm9703/xenosphere-rs/packages/xenosphere-core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
