[package]
name = "xenosphere"
version = "0.0.1-alpha.0"
edition = "2021"
authors = ["Steven Chm<stv.chm@gmail.com>"]
description = "Xenosphere, the cross-platform App Framework"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# This is the main dependency for the project
# re-export project crate
# xenosphere = { path = "../xenosphere" }
xenosphere-core = { path = "../xenosphere-core" }
xenosphere-macro = { path = "../xenosphere-macro" }
xenosphere-parser = { path = "../xenosphere-parser" }
