[package]
name = "xenosphere-macro"
version = "0.0.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = { workplace = true }
syn = { workplace = true }
