[package]
name = "xenosphere-macro"
version = "0.0.1-alpha.0"
edition = "2021"
description = "A macro function for handling Xenosphere framework"
license-file= "https://github.com/Stvchm9703/xenosphere-rs/blob/main/LICENSE"
repository = "https://github.com/Stvchm9703/xenosphere-rs/packages/xenosphere-macro"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = { workplace = true }
syn = { workplace = true }
quote = { workplace = true }
