[package]
name = "xenosphere-parser"
version = "0.0.1-alpha.1"
edition = "2021"
description = "A token parser for handling Xenosphere framework"
license-file = "LICENSE"
repository = "https://github.com/Stvchm9703/xenosphere-rs/packages/xenosphere-parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# proc-macro2 = { workplace = true, version = "1.0.79" }
syn = { workplace = true, version = "2.0.58", features = [
  "extra-traits",
  "full",
] }
quote = { workplace = true, version = "1.0.35" }
pest = { version = "2.7.11" }
pest_derive = { version = "2.7.11" }
tree-sitter = { version = "0.22.6" }
tree-sitter-c = { version = "0.21.4" }
tree-sitter-cuda = { version = "0.20.5" }
tree-sitter-cpp = { version ="0.22.2" }
tree-sitter-rust = { version = "0.21.2" }
tree-sitter-python = { version = "0.21" }
tree-sitter-javascript = { version = "0.21.4" }
tree-sitter-typescript = { version = "0.21.2" }
tree-sitter-go = { version = "0.21" }

anyhow = { workspace = true, version = "1.0.44" }
safetensors = { version = "0.4.3" }
polars = { version = "0.40", features = [
  "default",
  "lazy",
  "serde",
  "serde-lazy",
  "lazy",
  "avro",
  "json",
  "ipc",
  "csv",
  "parquet",
] }

serde = { version = "1.0.203", features = [
  "derive",
  "std",
] }

regex="*"
lazy_static="1.5"


[build-dependencies]
cc="*"
