[package]
name = "xenosphere-parser"
version = "0.0.1-alpha.1"
edition = "2021"
description = "A token parser for handling Xenosphere framework"
license-file= "LICENSE"
repository = "https://github.com/Stvchm9703/xenosphere-rs/packages/xenosphere-parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
proc-macro2 = { workplace = true , version = "1.0.79" }
syn = { workplace = true, version = "2.0.58", features = ["extra-traits", "full"] }
quote = { workplace=true, version = "1.0.35"}
