[package]
name = "xenosphere-parser"
version = "0.0.1-alpha.0"
edition = "2021"
description = "A token parser for handling Xenosphere framework"
license-file= "LICENSE"
repository = "https://github.com/Stvchm9703/xenosphere-rs/packages/xenosphere-parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
proc-macro2 = { workplace = true }
syn = { workplace = true }
