[package]
name = "xenosphere-service"
version = "0.0.0"
edition = "2024"
license-file.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
